datadog:
  apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  appKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  times:
    begin: -1
    end: 0
  tags:
    cluster: kube_cluster_name
    namespace: kube_namespace
    deployment: kube_deployment
    replicas: kubernetes_state.deployment.replicas
    cpu:
      limit: kubernetes.cpu.limits
      request: kubernetes.cpu.requests
      usage: kubernetes.cpu.usage.total
    memory:
      limit: kubernetes.memory.limits
      request: kubernetes.memory.requests
      usage: kubernetes.memory.usage
kubernetes:
  targets:
    - configPath: /repos/digode/kube-recal/kubeconfig
filters:
  kube_cluster_name: productionx
scales:
  cpu:
    request: 1.15
    limit: 1.6
  memory:
    request: 1.25
    limit: 2.0
