{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-recall.fullname" . }}
  annotations:
  {{- include "kube-recall.annotations" . | nindent 4 }}
  labels:
  {{- include "kube-recall.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
{{- end -}}
