apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-recall.fullname" . }}-startup
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- include "kube-recall.annotations" . | nindent 4 }}
  labels:
  {{- include "kube-recall.labels" . | nindent 4 }}
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: {{ include "kube-recall.fullname" . }}
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: {{ .Release.Name }}
  suspend: false
  template:
    metadata:
      annotations:
      {{- include "kube-recall.annotations" . | nindent 8 }}
      labels:
      {{- include "kube-recall.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Chart.Name }}-startup
        resources: {}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30