{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-recall.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "kube-recall.annotations" . | nindent 4 }}
  labels:
    {{- include "kube-recall.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end -}}